# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 21:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatLon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WaterFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.FloatField()),
                ('speed', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('time', models.TimeField(blank=True, verbose_name='Time')),
                ('latlon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.LatLon')),
            ],
        ),
        migrations.CreateModel(
            name='WaterLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('time', models.TimeField(blank=True, verbose_name='Time')),
                ('latlon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.LatLon')),
            ],
        ),
        migrations.AddField(
            model_name='soilmoisture',
            name='latlon',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='server.LatLon'),
            preserve_default=False,
        ),
    ]
